project:
  type: website
  resources:
    - "audio/**"
    - "data/**"

website:
  title: "Car Character"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: Story
      - href: exploration.qmd
        text: Exploration
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
