project:
  type: website
  resources:
    - "audio/**"
    - "data/**"
    - "scripts/**"
    - "images/**"
    - "1960s/**"
    - "1970s/**"
    - "1980s/**"
    - "1990s/**"
    - "2000s/**"
    - "2010s/**"
    - "2020s/**"

website:
  title: "Car Character"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: Story
      - href: color.qmd
        text: Color
      - href: shape.qmd
        text: Shape
      - href: sound.qmd
        text: Sound
      - href: exploration.qmd
        text: Exploration
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
